package org.fineract.iso20022.model.enums;

public enum OperationType {
    CREDIT_TRANSFER,
    DIRECT_DEBIT,
    REVERSAL,
    RETURN,
    CANCELLATION,
    LOAN_DISBURSEMENT,
    LOAN_REPAYMENT,
    STATUS_REQUEST,
    ACCOUNT_REPORT_REQUEST,
    MANDATE_INITIATION,
    MANDATE_AMENDMENT,
    ACCOUNT_OPENING,
    ACCOUNT_MODIFICATION,
    ACCOUNT_CLOSING
}
